id: tasks
label: Tasks
description: "Tasks context"
recommended: true
trustLevel: experimental
available: true
connectionTypeId: informatica-powercenter-soap
parameters:
  - type: DYNAMIC_SELECT
    id: repository
    label: Repository
    mandatory: true
    dynamicValues:
      script: ../dist/module.js
      function: getRepositories
  - type: DYNAMIC_SELECT
    id: folder
    label: Folder
    mandatory: true
    dynamicValues:
      script: ../dist/module.js
      function: getFolders
    dependsOn:
      - repository
  - type: DYNAMIC_SELECT
    id: workflow
    label: Workflow
    mandatory: true
    dynamicValues:
      script: ../dist/module.js
      function: getWorkflows
    dependsOn:
      - folder
  - type: DYNAMIC_SELECT
    id: service
    label: Integration service
    mandatory: true
    dynamicValues:
      script: ../dist/module.js
      function: getServices
    dependsOn:
      - workflow
  - type: STATIC_SELECT
    id: requestMode
    label: Request mode
    mandatory: true
    comment: Indicates the recovery strategy for the session task
    staticValues:
      - id: NORMAL
        label: NORMAL - Restarts a session without recovery
      - id: RECOVERY
        label: RECOVERY - Recovers a session
    dependsOn:
      - workflow
  - type: TEXT
    id: depth
    label: Depth for searching specific tasks
    mandatory: true
    comment: The number of levels within the workflow task hierarchy from which to get information on task instances. Must be a positive integer.
    dependsOn:
      - workflow
  - type: DYNAMIC_SELECT
    id: task
    label: Specific task
    mandatory: true
    dynamicValues:
      script: ../dist/module.js
      function: getTasks
    dependsOn:
      - depth
actions:
  start:
    script: ../dist/module.js
    function: start
  stop:
    script: ../dist/module.js
    function: stop
  getStatus:
    script: ../dist/module.js
    function: getStatus
  getLogs:
    script: ../dist/module.js
    function: getLogs
