name: Close issue on Jira

on:
    issues:
        types: [closed, deleted]

jobs:
    jira:
        runs-on: ubuntu-latest

        steps:
          - name: Dump GitHub context
            env:
              GITHUB_CONTEXT: ${{ toJson(github) }}
            run: echo "$GITHUB_CONTEXT"

          - name: Jira Login
            id: login
            uses: atlassian/gajira-login@master
            env:
                JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
                JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
                JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
          - name: Extract JIRA number
            id: extract_jira_number
            env:
              TITLE: ${{github.event.issue.title}}
            run: echo "::set-output name=jira_number::$(echo "$TITLE"| sed 's/.*\[\(${{ secrets.JIRA_PROJECT }}-[[:digit:]]\{1,\}\)\].*/\1/')"
          
          - name: Jira Close issue
            id: close_jira_issue
            uses: atlassian/gajira-transition@master
            with:
              issue: ${{ steps.extract_jira_number.outputs.jira_number }}
              transitionId: "${{ secrets.JIRA_CLOSE_TRANSITIONID }}"
